title:    Zehui Lin # your name (or website title) here

logo: "images/profile.JPG?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://www.linkedin.com/in/zehuilin/">LinkedIn </a>
  <a href="https://github.com/gebryo616">| GitHub</a>
  <a href=https://gebryo616.github.io/pdf/Resume.pdf>| Resume</a>
  </p>
  
  <p align="justify">
  Hi, I'm Jiawen Liang at Simon Business School, University of Rochester.
  <br><br>
  Currently, I am seeking data science opportunities. If you are interested in me and my analytical work, please reach out to me!
  <br><br>
  </p>
 
theme: jekyll-theme-minimal
google_analytics: UA-156201790-1
