title:    林 泽辉 # your name (or website title) here

logo: "image/profile.JPG?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="https://www.linkedin.com/in/zehuilin/">LinkedIn </a>
  <a href="https://github.com/gebryo616">| GitHub</a>
  <a href=https://gebryo616.github.io/pdf/Resume.pdf>| Resume</a>
  </p>
  
  <p align="justify">
  嘿，我是林泽辉，我是一个学习兴趣广泛并且热爱学习的人。
  <br><br>
  我感兴趣的学科有心理，金融，经济与数学。
  <br><br>
  其中我尤其感兴趣的领域有情绪学，流动性（liquidity，and credit system）& Markov theory.
  <br><br>
  除此之外我还热爱柔道，与巴西柔术。
  </p>
 
theme: jekyll-theme-minimal
google_analytics: UA-156201790-1
